### ISSUE TITLE
Trial expiration notification. What does this mean?

### ISSUE THREAD

**Issue by s-Pex** [s-Pex/VollemansBugs#14]
I got an e-mail telling me the trials for the Microsoft accounts have expired. What does this mean?

**Comment by Martijn735** [comment]
![image](https://user-images.githubusercontent.com/105886332/170080952-328bc972-104e-4bdc-aa95-bf0c417b853a.png)

**Comment by Martijn735** [comment]
This is with my account

**Comment by s-Pex** [comment]
Assigned new licenses to Martijn, Haley and Andrew. Left out Anna because she uses her own personal license. Moved to closed.
